name: Build and push Docker Image

on:
  push:
    branches:
      -main

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t app_demo:latest

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag app_demo:latest horiaoana89/app_demo:latest

      - name: Push Docker Image
        run: docker push horiaoana09/app_demo:latest
